### PR TITLE
feat: upgrade chakra-ui to v2.5.0 to fix Menu

### PR DESCRIPTION
**Pull request by mantariksh**
Upgrades to the latest version of `@chakra-ui/react` which contains a [helpful fix](https://github.com/chakra-ui/chakra-ui/pull/7315) for the `Menu` component.

### CODE REVIEW

**Comment by mantariksh** [comment]
build failed. meh

**Comment by karrui** [comment]
Some subtle changes in stories. Probably due to the new `displayNames` of the update. Do you want to fix it or should I? @mantariksh

**Comment by mantariksh** [comment]
@karrui probably faster if you do it tbh, I can't tell which ones to be fixed and which ones are false positives. the only difference I can see is that there's now some border radius where there shouldn't be.

**Comment by karrui** [comment]
Weird, only Chromatic shows the borderRadius, but the component itself in the storybook doesn't

**Comment by karrui** [comment]
Wow inadvertently fixed spacing bug for date range picker hehe

**Pull request merged**
